name: PR 


on:
  push:
    branches:
      - main

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            target_wasm/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Login docker
        run: docker login https://ghcr.io -u wquintal -p $GITHUB_ACCESS_TOKEN
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} 
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Dependency
        run: sudo apt-get install g++ make pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0 libwayland-dev libxkbcommon-dev && rustup component add rustfmt
      - name: Dependencies
        run: cargo vendor && (make dep_web || echo "ok")
      - name: Generate version number
        id: generate_version
        run: |
          # Get the latest tag
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          
          # Get the short SHA
          SHORT_SHA=$(git rev-parse --short HEAD)
          
          # Combine them for the version
          VERSION="${LATEST_TAG}-${SHORT_SHA}"
          
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
          
          echo "Generated version: $VERSION" 
      - name: Test
        run: make test
      - name: Style Check
        run: make format
      - name: Build web
        run:  APP_VERSION="${{ env.VERSION }}" make build_website TARGET=web PROFILE=prod
      - name: Build matchbox
        run: make build_docker_matchbox_server 
      - name: Publish docker matchbox
        run: make push_docker_matchbox_server
      - name: Publish docker website
        run: make push_docker_website
      - name: Update deployment
        run: doctl apps create-deployment 12321cca-c9b1-4e19-9961-3d5ebc8ff12a && doctl apps create-deployment a5542b50-f1f1-4b33-9fe6-f96cae8ff8cb